### ISSUE TITLE
Error after fivem update

### ISSUE THREAD

**Issue by Dragese** [ESX-Org/esx_status#11]
In a F8 console: invalid ref call attempt 1

**Comment by oogienl** [comment]
same here since update https://gyazo.com/4cb846f616ea271045a263f752d9f6c1

**Comment by sitamCZ** [comment]
The issue with esx_property and esx_status is caused by custom JS clientside script. 
Don't be confused with NUI/resource .js files, we are talking about client_script which is JavaScript file instead of lua.

How to trace it down:
The easiest method for me was to:
```cd FIVEM_RESOURCES_DIR```
then

```find . -name "__resource.lua" -print0 | xargs -0 grep ".js | grep client```

Stop this resource and you will be fine.

Confirmed resources which are breaking the esx_status/property:
https://forum.fivem.net/t/release-js-radio/52121


Once again, remember it's about JS file which is defined as client side script. All of the nui js files are fine, as they are just part of the specific resource.

Thanks to @iridium from FiveM's staff for helping out!

**Comment by Dragese** [comment]
> The issue with esx_property and esx_status is caused by custom JS clientside script.
> Don't be confused with NUI/resource .js files, we are talking about client_script which is JavaScript file instead of lua.
> 
> How to trace it down:
> The easiest method for me was to:
> `cd FIVEM_RESOURCES_DIR`
> then
> 
> `find . -name "__resource.lua" -print0 | xargs -0 grep ".js | grep client`
> 
> Stop this resource and you will be fine.
> 
> Confirmed resources which are breaking the esx_status/property:
> https://forum.fivem.net/t/release-js-radio/52121
> 
> Once again, remember it's about JS file which is defined as client side script. All of the nui js files are fine, as they are just part of the specific resource.
> 
> Thanks to @iridium from FiveM's staff for helping out!

The same problem breaking resource:
https://forum.fivem.net/t/release-generic-dui-2d-3d-renderer/131208
